# 0x05-python-exceptions
project for python exceptions
* exception is an error encountered through executions while all sytax error has been taken care of

## tasks and duties

| file | prototype | duty |
| -----| ---------| -----|
| 0-safe_print_list.py | def safe_print_list(my_list=[], x=0): | prints x elements of a list |
| 1-safe_print_integer.py | def safe_print_integer(value): | prints an integer with "{:d}".format() |
| 2-safe_print_list_integers.py | def safe_print_list_integers(my_list=[], x=0): |  prints the first x elements of a list and only integers |
| 3-safe_print_division.py | def safe_print_division(a, b): | divides 2 integers and prints the result |
| 4-list_division.py | def list_division(my_list_1, my_list_2, list_length): | divides element by element 2 lists |
| 5-raise_exceptions.py | def raise_exception(): | function that raises a type exception |
| 6-raise_exception_msg.py | def raise_exception_msg(message=""): | function that raises a name exception with a message |
| 100-safe_print_integer_err.py | def safe_print_integer_err(value): | function that prints an integer and error in stdrr |
| 101-safe_function.py | def safe_function(fct, *args): | function that executes a function safely |
| 102-magic_calculation.py | def magic_calculation(a, b): | does the bytecode |
